baseURL = "https://sqrtminusone.xyz/"
languageCode = "en-us"
title = "SqrtMinusOne"
staticDir = ["static"]

[params]
  author = "SqrtMinusOne"
  description = "Freedom is a state of mind"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = "logo.svg"
  [params.footer]
    text = "Pavel Korytov, 2024"
    license = ""
    licenseURL = "https://creativecommons.org/licenses/by/4.0/legalcode"
    [[params.footer.links]]
      text = "Licensed under CC-BY 4.0"
      url = "https://creativecommons.org/licenses/by/4.0/legalcode"
    [[params.footer.links]]
      text = "Uses Plausible Analytics"
      url = "https://plausible.io/"

  mainSections = ['posts']

[permalinks]
  "/" = "/:filename"

[menu]
    [[menu.main]]
      name = "Index"
      url = "/"
      weight = 1
    [[menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 1
    [[menu.main]]
      name = "Emacs packages"
      url = "/emacs-packages/"
    [[menu.main]]
      name = "Configs"
      url = "/configs/readme"


[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files