baseURL = "https://sqrtminusone.xyz/"
languageCode = "en-us"
title = "SqrtMinusOne"
theme = "researcher"
staticDir = ["static"]

[params]
  author = "SqrtMinusOne"
  description = "Freedom is a state of mind"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  # logo = "logo.svg"
  [params.footer]
    text = "Pavel Korytov, 2022"
  mainSections = ['posts']

[permalinks]
  "/" = "/:filename"

[menu]
    [[menu.main]]
      name = "Index"
      url = "/"
      weight = 1
    [[menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 1
    [[menu.main]]
      name = "Configs"
      url = "/configs/readme"


[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files