version: "3.5"
services:
  sqrtminusone.xyz:
    restart: unless-stopped
    container_name: "sqrtminusone.xyz"
    build: .
    ports:
      # - 8080:8080
      - 8081:8000
    volumes:
      - sqrtminusone_serve:/usr/share/nginx/html
volumes:
  sqrtminusone_serve: {}
