#+HUGO_BASE_DIR: ../..
#+HUGO_SECTION:
#+TITLE: Curriculum Vitae
#+HUGO_CUSTOM_FRONT_MATTER: :norss true :private true


* Contact Details
*Pavel V. Korytov*
- e-mail: [[mailto:thexcloud@gmail.com][thexcloud@gmail.com]] (personal), [[mailto:pvkorytov@etu.ru][pvkorytov@etu.ru]] (corporate)
- GitHub: [[https://github.com/SqrtMinusOne][https://github.com/SqrtMinusOne]]
- Mastodon: [[https://emacs.ch/@sqrtminusone][https://emacs.ch/@sqrtminusone]]
- Telegram: [[https://t.me/SqrtMinusTwo][https://t.me/SqrtMinusTwo]]

* Summary
Current positions:
- Graduate student of [[https://etu.ru/en/university/][Saint-Petersburg Electrotechnical University]] (ETU "LETI")
- Assistant Professor at [[https://etu.ru/en/study/faculties/faculty-of-computing-technologies-and-informatics/departments/department-of-software-engineering-and-computer-applications][Department of Software Engineering and Computer Applications]]
- Full-stack developer at Information Systems Department.

Developing information systems for the university. Doing research on the intersection of Natural Language Processing methods and Recommender Systems and teaching students in the meantime.

* Education
*Pursuing a degree of Candidate of Engineering Sciences* (2022 - current)
@@html:<div class="table-no-header">@@
|--------------------+-----------------------------------------------------------------------------------------------|
| Specialty          | 2.3.5 Mathematical and Software Support For Computer Systems, Complexes and Computer Networks |
| Supervisor         | Ivan I. Kholod                                                                                |
| Department         | Department of Information Systems                                                             |
| Faculty            | Faculty of Computer Science and Technology                                                    |
| Dissertation title | Examination of Application of Federated Learning For Text Analysis in Recommender Systems     |
@@html:</div>@@

@@html:<hr />@@

*Master's Degree* (2020 - 2022)
@@html:<div class="table-no-header">@@
|--------------+----------------------------------------------------------------------------|
| Specialty    | 09.04.04 Software Engineering                                              |
| Department   | Department of Software Engineering and Computer Applications               |
| Faculty      | Faculty of Computer Science and Technology                                 |
| Thesis title | Application of Text Analysis Methods to Recommend Educational Trajectories |
@@html:</div>@@

@@html:<hr />@@

*Bachelor's Degree* (2016 - 2020)
@@html:<div class="table-no-header">@@
|--------------------+-----------------------------------------------------------------------------|
| Specialty          | 09.03.04 Software Engineering                                               |
| Department         | Department of Software Engineering and Computer Applications                |
| Faculty            | Faculty of Computer Science and Technology                                  |
| Thesis title       | Development of the Software of Generation of Data Accounting System Mockups |
@@html:</div>@@

* Professional History
*Full-stack developer at Information Systems Department of ETU "LETI"* (2020 - current)

Digitalizing processes in the university in a team of ~10 colleagues (currently 12).

My responsibilities involve: database & architecture design, back- (primarily) and frontend development, deployment work, assisting/directing other developers, some analytical work.

All the systems are available at [[https://digital.etu.ru/main/][https://digital.etu.ru/main/.]]

@@html:<hr />@@

*Assistant Professor at Department of Software Engineering and Computer Applications of ETU "LETI"* (2023 - current)

Teaching courses to students (I started earlier than I got the position):
- Databases (2021 - current): lectures on the database design theory, SQL, ORMs, etc.
- DevOps (2023 - current): mostly checking student works on Docker & CI/CD.

Currently an acting supervisor for 3 students (1 bachelor's and 2 master's); 5 in total so far.

* Open Source Work
- I authored 13 packages for [[https://www.gnu.org/software/emacs/][GNU Emacs]] (see [[https://sqrtminusone.xyz/emacs-packages/][My Emacs Packages]]), 10 of which are available in [[https://melpa.org/#/][MELPA]]
- I maintain several bridges in the [[https://github.com/RSS-Bridge/rss-bridge][RSS Bridge]] project

* Skills
- *Languages*: _Russian_ (native), _English_ (~B2/C1)
- *RDBMS*:
  - Primarily: _PostgreSQL_
  - Also worked with: _SQLite_, _MySQL_, _MariaDB_, _MSSQL_.
- *NoSQL*:
  - Primarily: _Redis_, _Apache Drill_;
  - Also worked with: _MongoDB_, _Neo4j_
- *OLAP*: _ClickHouse_; also worked with _Apache Druid_
- *Programming languages*:
  - Primarily: _Python_, _JavaScript_, _TypeScript_, _HTML/CSS_, _Emacs Lisp_
  - Also worked with: _C_, _C++ (Qt)_, _PHP_, _Java 8_, _MASM_, _HLASM_, _Clojure_, _Scheme_, _Hy_, _GNU Octave_.
- *Technologies/Frameworks*:
  - ORMs: _Sequelize_ (node.js), _SQLAlchemy_ (Python)
  - Backend: _express.js_, _nest.js_, _Flask_ (Python)
  - Frontend: _Vue.js_, _Bootstrap_, _Sass_
  - Data processing: _numpy_, _pandas_, _matplotlib_, _streamlit_
  - ML: _scikit-learn_, _spacy_; worked with _pytorch_, _transformers_
- *DevOps*:
  - Web server: _nginx_
  - CI/CD: _Jenkins_, _GitHub Actions_, _GitLab Actions_.
  - Monitoring/Analytics: _Prometheus_, _Grafana_, _Metabase_.
  - Misc: _Docker_, _POSIX shell_ & _bash_.
- *Misc*: _LaTeX_, _GNU Emacs_, _GNU Guix_

* Publications
- @@html:<div class="text-ru">@@ А. Н. Матвеев and П. В. Корытов, “Описание разработки микросервиса для семантического сопоставления текстов,” in Сборник XI конференции “Наука настоящего и будущего,” СПб.: СПбГЭТУ «ЛЭТИ», 2023, pp. 216–262. @@html:</div>@@
- I. I. Kholod, P. V. Korytov, and M. V. Sorochina, “Application of Neural Network Keyword Extraction Methods for Student’s CV Compilation from Discipline Work Programs,” in 2023 XXVI International Conference on Soft Computing and Measurements (SCM), СПб.: IEEE, May 2023, pp. 143–146. doi: 10.1109/SCM58628.2023.10159061.
- P. V. Korytov and I. I. Kholod, “Application of Text Analysis Methods to Recommend Student Choices,” in 2022 XXV International Conference on Soft Computing and Measurements (SCM), СПб.: IEEE, May 2022, pp. 107–110. doi: 10.1109/SCM55405.2022.9794830.
- R. R. Fatkieva and P. V. Korytov, “Assessment of Applicability of Discrete Situational Networks for Information Transmission in Intelligent Transport Networks,” Autom. Doc. Math. Linguist., vol. 56, no. 2, pp. 70–75, Apr. 2022, doi: 10.3103/S0005105522020029.
- @@html:<div class="text-ru">@@ М. О. Доброхвалов, П. В. Корытов, С. И. Степанова, А. А. Тарасова, and Ар. Ю. Филатов, “Анализ подходов к моделированию систем  массового обслуживания,” Известия ЛЭТИ, vol. 5, pp. 56–64, 2021. @@html:</div>@@
- I. I. Kholod, M. V. Kovynev, I. S. Grigoriev, and P. V. Korytov, “Developing a single sign-on for information systems,” Software Journal: Theory and Applications, vol. 3, 2021.
- @@html:<div class="text-ru">@@ И. И. Холод, В. С. Иванов, И. С. Григорьев, П. В. Корытов, and М. В. Ковынев, “Опыт автоматизации процесса составления расписания в вузе,” Cloud of Science, vol. 7, no. 4, pp. 844–865, 2020. @@html:</div>@@
- @@html:<div class="text-ru">@@ П. В. Корытов and С. А. Беляев, “Опыт создания программы автоматической  генерации web-приложений по формальным требованиям,” Cloud of Science, vol. 7, no. 3, pp. 559–576, 2020. @@html:</div>@@
- G. O. Medvedev, D. M. Klionskiy, N. V. Razmochaeva, and P. V. Korytov, “Investigation of Distance Digital Signal Processing Courses based on Modern Programming Languages,” in 2020 9th Mediterranean Conference on Embedded Computing (MECO), Budva, Montenegro: IEEE, Jun. 2020, pp. 1–4. doi: 10.1109/MECO49872.2020.9134327.
- P. V. Korytov, S. A. Belyaev, A. V. Ekalo, and E. V. Postnikov, “Development of the Program for Creating Data Accounting Software Systems Mockups,” in 2020 IEEE Conference of Russian Young Researchers in Electrical and Electronic Engineering (EIConRus), СПб.: IEEE, Jan. 2020, pp. 359–362. doi: 10.1109/EIConRus49466.2020.9039515.

* Other Interests
My layperson interests include, in no particular order: philosophy of AI, philosophy of rationality and cognitive biases, workings of evolution, eastern religions.

I love the Making Sense podcast.
